version: "3"

services:
  postgres:
    image: postgres:16.0-alpine
    env_file: ../.env
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - ${DATABASE_PORT}

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_SETUP_CONNECTION: |
        {
          "Servers": {
            "Local Postgres": {
              "Name": "Local Postgres",
              "Group": "Local",
              "Host": "postgres",
              "Port": ${DATABASE_PORT},
              "MaintenanceDB": "${DATABASE_NAME}",
              "Username": "${DATABASE_USER}",
              "SSLMode": "prefer",
              "Password": "${DATABASE_PASSWORD}"
            }
          }
        }
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped